import Config

# Configure your database
config :sensocto, Sensocto.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "sensocto_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# postgresql://neondb_owner:npg_JYAldE0u5Xmk@ep-dark-mountain-a2nvkl0o-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
# config :sensocto, Sensocto.Repo,
#   database: "neondb",
#   username: "neondb_owner",
#   password: "npg_JYAldE0u5Xmk",
#   hostname: "ep-dark-mountain-a2nvkl0o-pooler.eu-central-1.aws.neon.tech",
#   ssl: [cacerts: :public_key.cacerts_get()]

config :tailwind,
  version: "3.4.0",
  sensocto: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../assets", __DIR__)
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sensocto, SensoctoWeb.Endpoint,
  # url: [host: "Adrians-MacBook-Pro.local", port: 4001, scheme: "https"],
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # http: [ip: {127, 0, 0, 1}, port: 4000],
  http: [ip: {0, 0, 0, 0}, port: 4000],
  https: [
    port: 4001,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "0EViyDRvvk8yO72jkyPMGrvTm0iqLuDckbHUdqrBkZb2Td2NDLkS590D08E9qLL6",
  watchers: [
    node: ["build.js", "--watch", cd: Path.expand("../assets", __DIR__)],
    tailwind: {Tailwind, :install_and_run, [:sensocto, ~w(--watch)]},
    node: ["build.js", "--watch", cd: Path.expand("../assets", __DIR__)]
    # esbuild: {Esbuild, :install_and_run, [:sensocto, ~w(--sourcemap=inline --watch)]},

    # live_svelte: {LiveSvelte, :init, []}
  ]

config :live_debugger,
  browser_features?: true,
  assets_url: "http://localhost:4007/assets/live_debugger/browser_features.js"
# config :live_debugger,
# ip: {127, 0, 0, 1}, # IP on which LiveDebugger will be hosted
# port: 4007, # Port on which LiveDebugger will be hosted
# secret_key_base: <SECRET_KEY_BASE>, # Secret key used for LiveDebugger.Endpoint
# signing_salt: "your_signing_salt", # Signing salt used for LiveDebugger.Endpoint
# adapter: Bandit.PhoenixAdapter # Adapter used in LiveDebugger.Endpoint

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :sensocto, SensoctoWeb.Endpoint,
  live_reload: [
    web_console_logger: false,
    notify: [
      live_view: [
        ~r"assets/svelte/*.svelte$",
        ~r"lib/sensocto_web/core_components.ex$",
        ~r"lib/sensocto_web/(live|components)/.*(ex|heex)$"
      ]
    ],
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/sensocto_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"lib/sensocto_web/(live|components)/.*neex$",
      ~r"lib/sensocto_web/styles/.*ex$",
      ~r"priv/static/*.styles$"
    ]
  ]

config :logger,
  level: :debug,
  backends: [{FlexLogger, :logger_name}]

config :logger, :logger_name,
  logger: :console,
  # this is the loggers default level
  # default_level: :info,
  # override default levels
  level_config: [
    # [module: Sensocto.SimpleSensor, level: :debug],
    # [module: Sensocto.AttributeStorer, level: :debug],
    [module: SensoctoWeb.SensorDataChannel, level: :debug],
    [module: Sensocto.Otp.RepoReplicator, level: :debug]
    # [module: Phoenix.Logger, level: :debug],
    # [module: SensoctoWeb.Plugs.RequestLogger, level: :debug],
    # [module: SensoctoWeb.Live.LvnEntryLive, level: :debug],
    # [module: Phoenix.LiveView.Channel, level: :debug]
    # [module: SensoctoWeb.Live.PlaygroundLive, level: :debug]
    # [module: SensoctoWeb.IndexLive, level: :debug],
    # [module: SensoctoWeb.Live.BaseComponents, level: :debug]
  ],
  # backend specific configuration
  # format: "DEV [$time] [$level] $message\n"
  format: "DEV [$level] $message [ $metadata ] \n",
  # [$time][$node][$level]
  metadata: [:node, :pid, :file, :function, :line]

# https://elixirforum.com/t/logger-format/8616/2

config :ash_authentication, debug_authentication_failures?: true

# Enable dev routes for dashboard and mailbox
config :sensocto, dev_routes: true, token_signing_secret: "9fhsVJSpOCeIGPWB7AL7/Q3Emgy34xJK"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable debug attributes for Tidewave integration
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Use local adapter for development - emails viewable at /dev/mailbox
config :sensocto, Sensocto.Mailer, adapter: Swoosh.Adapters.Local

#

# LVN_ACTIVATION config :live_view_native_stylesheet,
# LVN_ACTIVATION   annotations: true,
# LVN_ACTIVATION   pretty: true
