import Config

# Configure your database
# For Neon.tech: Set DEV_DATABASE_* environment variables
# For local PostgreSQL: Use defaults (postgres/postgres/localhost)
config :sensocto, Sensocto.Repo,
  database: System.get_env("DEV_DATABASE_NAME", "sensocto_dev"),
  username: System.get_env("DEV_DATABASE_USER", "postgres"),
  password: System.get_env("DEV_DATABASE_PASSWORD", "postgres"),
  hostname: System.get_env("DEV_DATABASE_HOST", "localhost"),
  ssl:
    if(System.get_env("DEV_DATABASE_SSL") == "true",
      do: [cacerts: :public_key.cacerts_get()],
      else: false
    ),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  queue_target: 5000,
  queue_interval: 1000

# Read replica - in dev, points to same database
config :sensocto, Sensocto.Repo.Replica,
  database: System.get_env("DEV_DATABASE_NAME", "sensocto_dev"),
  username: System.get_env("DEV_DATABASE_USER", "postgres"),
  password: System.get_env("DEV_DATABASE_PASSWORD", "postgres"),
  hostname: System.get_env("DEV_DATABASE_HOST", "localhost"),
  ssl:
    if(System.get_env("DEV_DATABASE_SSL") == "true",
      do: [cacerts: :public_key.cacerts_get()],
      else: false
    ),
  pool_size: 5

# Local PostgreSQL (uncomment to use local dev database instead of Neon)
# config :sensocto, Sensocto.Repo,
#   username: "postgres",
#   password: "postgres",
#   hostname: "localhost",
#   database: "sensocto_dev",
#   stacktrace: true,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 20,
#   queue_target: 5000,
#   queue_interval: 1000
#
# config :sensocto, Sensocto.Repo.Replica,
#   username: "postgres",
#   password: "postgres",
#   hostname: "localhost",
#   database: "sensocto_dev",
#   pool_size: 10

config :tailwind,
  version: "3.4.0",
  sensocto: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../assets", __DIR__)
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sensocto, SensoctoWeb.Endpoint,
  # url: [host: "Adrians-MacBook-Pro.local", port: 4001, scheme: "https"],
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # http: [ip: {127, 0, 0, 1}, port: 4000],
  http: [ip: {0, 0, 0, 0}, port: 4000],
  https: [
    port: 4001,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  check_origin: ["http://localhost:4000", "https://localhost:4001"],
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    System.get_env(
      "DEV_SECRET_KEY_BASE",
      "dev_only_secret_key_base_not_for_production_use_generate_new_one"
    ),
  watchers: [
    node: ["build.js", "--watch", cd: Path.expand("../assets", __DIR__)],
    tailwind: {Tailwind, :install_and_run, [:sensocto, ~w(--watch)]},
    node: ["build.js", "--watch", cd: Path.expand("../assets", __DIR__)]
    # esbuild: {Esbuild, :install_and_run, [:sensocto, ~w(--sourcemap=inline --watch)]},

    # live_svelte: {LiveSvelte, :init, []}
  ]

config :live_debugger,
  browser_features?: false

# config :live_debugger,
# ip: {127, 0, 0, 1}, # IP on which LiveDebugger will be hosted
# port: 4007, # Port on which LiveDebugger will be hosted
# secret_key_base: <SECRET_KEY_BASE>, # Secret key used for LiveDebugger.Endpoint
# signing_salt: "your_signing_salt", # Signing salt used for LiveDebugger.Endpoint
# adapter: Bandit.PhoenixAdapter # Adapter used in LiveDebugger.Endpoint

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :sensocto, SensoctoWeb.Endpoint,
  live_reload: [
    web_console_logger: false,
    notify: [
      live_view: [
        ~r"assets/svelte/*.svelte$",
        ~r"lib/sensocto_web/core_components.ex$",
        ~r"lib/sensocto_web/(live|components)/.*(ex|heex)$"
      ]
    ],
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/sensocto_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"lib/sensocto_web/(live|components)/.*neex$",
      ~r"lib/sensocto_web/styles/.*ex$",
      ~r"priv/static/*.styles$"
    ]
  ]

config :logger,
  level: :debug,
  backends: [{FlexLogger, :logger_name}]

config :logger, :logger_name,
  logger: :console,
  # this is the loggers default level
  default_level: :info,
  # override default levels
  level_config: [
    # Silence verbose simulator/sensor debug logs
    [module: Sensocto.Simulator.AttributeServer, level: :info],
    [module: Sensocto.Simulator.SensorServer, level: :info],
    [module: Sensocto.Simulator.DataServer, level: :info],
    [module: Sensocto.Otp.SimpleSensor, level: :info],
    [module: Sensocto.Otp.RepoReplicator, level: :info],
    [module: Sensocto.SimpleSensor, level: :info],
    # Silence verbose channel/LiveView debug logs
    [module: SensoctoWeb.SensorDataChannel, level: :info],
    [module: SensoctoWeb.Live.Components.AttributeComponent, level: :info],
    [module: SensoctoWeb.StatefulSensorLive, level: :info],
    [module: SensoctoWeb.IndexLive, level: :info]
  ],
  # backend specific configuration
  # format: "DEV [$time] [$level] $message\n"
  format: "DEV [$level] $message [ $metadata ] \n",
  # [$time][$node][$level]
  metadata: [:node, :pid, :file, :function, :line]

# https://elixirforum.com/t/logger-format/8616/2

config :ash_authentication, debug_authentication_failures?: true

# Enable dev routes for dashboard and mailbox
config :sensocto,
  dev_routes: true,
  token_signing_secret: System.get_env("DEV_TOKEN_SIGNING_SECRET", "dev_only_token_secret")

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable debug attributes for Tidewave integration
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Use local adapter for development - emails viewable at /dev/mailbox
config :sensocto, Sensocto.Mailer, adapter: Swoosh.Adapters.Local

#

# LVN_ACTIVATION config :live_view_native_stylesheet,
# LVN_ACTIVATION   annotations: true,
# LVN_ACTIVATION   pretty: true

# Simulator starts and auto-starts connectors for testing
config :sensocto, :simulator,
  enabled: true,
  autostart: true,
  config_path: "config/simulators.yaml"

# OpenAPI spec - disable caching in development for faster iteration
config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache

# Memory pressure configuration for development
# In dev, memory pressure should not trigger protection until very high (95%)
# This allows more aggressive testing without constant throttling
config :sensocto, :memory_pressure,
  # Start protection at 95% memory pressure (very lenient for dev)
  protection_start: 0.95,
  # Critical memory level
  critical: 0.98
