import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sensocto, SensoctoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Sensocto.Finch

config :sensocto, Sensocto.Mailer,
  adapter: Swoosh.Adapters.SMTP2GO,
  api_key: System.get_env("SMTP2GO_APIKEY")

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info



# only for dummy prod
config :sensocto, SensoctoWeb.Endpoint,
  # url: [host: "Adrians-MacBook-Pro.local", port: 4001, scheme: "https"],
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # http: [ip: {127, 0, 0, 1}, port: 4000],
  http: [ip: {0, 0, 0, 0}, port: 4000],
  https: [
    port: 4001,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  check_origin: false


# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
