import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sensocto, SensoctoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Sensocto.Finch

config :sensocto, Sensocto.Mailer,
  adapter: Swoosh.Adapters.SMTP2GO,
  api_key: System.get_env("SMTP2GO_APIKEY") || ""

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Production endpoint configuration
# IMPORTANT: Set PHX_HOST environment variable to your domain
config :sensocto, SensoctoWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4000],
  https: [
    port: 4001,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  # Enable origin checking in production - set PHX_HOST to your domain
  check_origin: [
    "https://sensocto.ddns.net",
    "https://" <> (System.get_env("PHX_HOST") || "localhost")
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
