defmodule Sensocto.Repo.Migrations.AddAttributeData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sensors_attribute_data, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sensor_id, :text, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :attribute_id, :text, null: false
      add :payload, :map, null: false, default: %{}
    end

    create unique_index(:sensors_attribute_data, [:id],
             name: "sensors_attribute_data_unique_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sensors_attribute_data, [:id],
                     name: "sensors_attribute_data_unique_index"
                   )

    drop table(:sensors_attribute_data)
  end
end
