defmodule Sensocto.Repo.Migrations.Test do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sensors) do
      modify :sensor_type_id, :uuid, null: true
    end
  end

  def down do
    alter table(:sensors) do
      modify :sensor_type_id, :uuid, null: false
    end
  end
end
