defmodule Sensocto.Repo.Migrations.User do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:sensors, [:id, :mac_address], name: "sensors_unique_index")

    create unique_index(:sensors, [:id], name: "sensors_unique_index")
  end

  def down do
    drop_if_exists unique_index(:sensors, [:id], name: "sensors_unique_index")

    create unique_index(:sensors, [:id, :mac_address], name: "sensors_unique_index")
  end
end
