defmodule Sensocto.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sensors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :sensor_type_id, :uuid, null: false
      add :mac_address, :text
      add :configuration, :map
      add :connector_id, :uuid
      add :sensor_type_rel_id, :uuid
    end

    create unique_index(:sensors, [:id, :mac_address], name: "sensors_unique_index")
  end

  def down do
    drop_if_exists unique_index(:sensors, [:id, :mac_address], name: "sensors_unique_index")

    drop table(:sensors)
  end
end
