defmodule Sensocto.Repo.Migrations.CreateConnectorsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:connectors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sensors) do
      modify :connector_id,
             references(:connectors,
               column: :id,
               name: "sensors_connector_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:sensors, [:connector_id])

    alter table(:connectors) do
      add :name, :text, null: false
      add :connector_type, :text, null: false
      add :configuration, :map
      add :last_seen_at, :utc_datetime_usec
      add :status, :text, null: false, default: "offline"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "connectors_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:connectors, [:user_id, :name],
             name: "connectors_unique_name_per_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:connectors, [:user_id, :name],
                     name: "connectors_unique_name_per_user_index"
                   )

    drop constraint(:connectors, "connectors_user_id_fkey")

    alter table(:connectors) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :last_seen_at
      remove :configuration
      remove :connector_type
      remove :name
    end

    drop_if_exists index(:sensors, [:connector_id])

    drop constraint(:sensors, "sensors_connector_id_fkey")

    alter table(:sensors) do
      modify :connector_id, :uuid
    end

    drop table(:connectors)
  end
end
