defmodule Sensocto.Repo.Migrations.DefaultIsPublicToFalse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :is_public, :boolean, default: false
    end
  end

  def down do
    alter table(:users) do
      modify :is_public, :boolean, default: true
    end
  end
end
