defmodule Sensocto.Repo.Migrations.CreateGuidedSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:guided_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :guide_user_id, :uuid, null: false
      add :follower_user_id, :uuid
      add :room_id, :uuid
      add :invite_code, :text, null: false
      add :drift_back_seconds, :bigint, null: false, default: 15
      add :started_at, :utc_datetime_usec
      add :ended_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:guided_sessions, [:invite_code],
             name: "guided_sessions_unique_invite_code_index"
           )
  end

  def down do
    drop_if_exists unique_index(:guided_sessions, [:invite_code],
                     name: "guided_sessions_unique_invite_code_index"
                   )

    drop table(:guided_sessions)
  end
end
