defmodule Sensocto.Repo.Migrations.AddSkeletonCompositeEnabled do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :skeleton_composite_enabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:rooms) do
      remove :skeleton_composite_enabled
    end
  end
end
