defmodule Sensocto.Repo.Migrations.AddIntimateTrustedToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :intimate_trusted, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :intimate_trusted
    end
  end
end
